[dependencies]
pyo3 = "0.19.0"

[lib]
name = "prqrs"
crate-type = ["cdylib"]

[package]
name = "prqrs"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
